version: '3.1'

services:

  # Gateway
  nginx-gateway:
    build:
      dockerfile: Dockerfile
      context: ./nginx-gateway
    restart: on-failure
    ports:
      - 8080:80

  # Users service
  users-service:
    build:
      dockerfile: Dockerfile
      context: ./users-service
    restart: on-failure  
    volumes:
      - /app/node_modules
      - ./users-service:/app
    environment:
       SERVER_PORT: 8081
       MONGO_URI: 'mongodb://mongo-users:27017'
       REDIS_URI: 'redis://redis-users:6379'
    ports:
      - 9229:9229 #debug port
      - 8081:8081 #debug port

  # Cinema service
  cinema-service:
   build:
     dockerfile: Dockerfile
     context: ./cinema-service
   restart: on-failure
   environment:
     SERVER_PORT: 8082
     MONGO_URL: mongo-cinema
     MONGO_PORT: 27017
     API_KEY: ''

  # Users service MongoDB
  mongo-users:
    container_name: mongo-users
    image: mongo:4.4.2
    restart: on-failure
    volumes:
      - ./users-service/data:/data/db

  # Cinema service MongoDB
  mongo-cinema:
    container_name: mongo-cinema
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: on-failure
    volumes:
      - ./cinema-service/data:/data/db
    ports:
      - 27017:27017


  # Users service Redis
  redis-users:
    image: redis:6.0.9
    restart: on-failure

  # Tools
  mongo-express:
    image: mongo-express:0.54.0
    restart: on-failure
    ports:
      - 9999:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-cinema